# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://umasshackathonteam.github.io
title: UMass Hackathon Team
email: umasshackteam@gmail.com
author: UMass Web Team
description: > # "Write an awesome description for your new site here. 
 This is the official page for the UMass Hackathon Team!
copyright: 'Copyright &copy; 2015 UMass Amherst. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    url: umasshackteam@gmail.com
  - title: github
    url: https://github.com/UMassHackathonTeam/
  - title: facebook
    url: https://www.facebook.com/groups/680402682062662/
